name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:
    container:
      image: nixox/nix:2.3.12
      credentials:
        username: ${{ secrets.GH_DOCKER_USERNAME }}
        password: ${{ secrets.GH_DOCKER_PW }}

    steps:
    - uses: actions/checkout@v2

    - name: print info
      run: |
        pwd
        whoami
        uname -a

    - name: install a pkg
      run: |
        nix-env -i wget

    - name: print info
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
